apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: gitops-nginx
    count: 5

labels:
  - pairs:
      environment: prod

patches:
  - path: service-patch.yaml
